import {
  cilVerticalAlignBottom,
  cilSnowflake,
  cilThumbUp,
  cilChildFriendly,
  cilBriefcase,
  cilDollar,
  cilGraph,
  cilSettings,
  cilStar,
  cilCarAlt,
  cilWalk,
  cilElevator,
  cilUserFollow,
  cilHouse,
  cilHome,
  cilGlobeAlt,
  cilLanguage,
  cilHeart,
  cilShieldAlt,
  cilPeople,
  cilSmile,
  cilMap,
  cilSun,
  cilMusicNote,
  cilLaptop,
  cilCoffee,
  cilFactory,
  cilTag,
  cilChartLine,
  cilBusAlt,
  cilClock,
  cilTerrain,
} from '@coreui/icons';

import { helicopter } from '../../icons/helicopter';

const typeNameToIcon = {
  digital_nomad_score: cilLaptop,
  seasonal_worker_score: cilBriefcase,
  family_vacation_score: cilChildFriendly,
  affordability: cilDollar,
  money_saving_potential: cilGraph,
  snow_quality: cilSnowflake,
  backcountry_accessibility: cilMap,
  slackcountry_accessibility: cilMap,
  nearby_vehicle_access: cilCarAlt,
  avalanche_safety: cilShieldAlt,
  fresh_tracks: cilWalk,
  lift_access: cilElevator,
  uncrowded: cilUserFollow,
  expert_terrain: cilStar,
  terrain_park: cilStar,
  child_friendly: cilChildFriendly,
  livability: cilHome,
  housing_availability: cilHouse,
  job_availability: cilBriefcase,
  summer_activities: cilSun,
  english_level: cilGlobeAlt,
  local_language_non_essential: cilLanguage,
  lgbt_friendly: cilHeart,
  cannabis_friendly: cilShieldAlt,
  international_ratio: cilPeople,
  gender_ratio: cilPeople,
  positive_vibes: cilSmile,
  camper_friendly: cilMap,
  night_life: cilMusicNote,
  co_working_spaces: cilFactory,
  cafes_to_work_from: cilCoffee,
  co_working_culture: cilFactory,
  snow_reliability: cilSnowflake,
  average_annual_snowfall: cilSnowflake,
  elevation_peak: cilTerrain,
  number_of_runs: cilChartLine,
  number_of_lifts: cilElevator,
  skiable_terrain: cilTerrain,
  vertical_drop: cilVerticalAlignBottom,
  longest_run: cilMap,
  terrain_expert: cilStar,
  terrain_intermediate: cilStar,
  terrain_beginner: cilStar,
  is_dry_slope: cilTag,
  snow_making: cilSettings,
  has_cross_country_skiing: cilWalk,
  has_helicopter_skiing: helicopter,
  night_skiing: cilClock,
  scenary: cilTerrain,
  ski_in_ski_out: cilWalk,
  ski_facilities: cilBusAlt,
  altitude_from: cilTerrain,
  altitude_to: cilTerrain,
};

const getTypeIcon = (typeName) => typeNameToIcon[typeName] || cilThumbUp;

export default getTypeIcon;
