version: 2.1

orbs:
  codecov: codecov/codecov@3.3.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.17.0-browsers
    steps:
      - checkout
      - run:
          name: Check Node.js version
          command: node --version
      - restore_cache:
          keys:
            - v2-npm-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v2-npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - /root/.cache/Cypress
      - run: npm run lint
      - run: npm run test:jest
      - run: npm run test:e2e
      - run: npm run coverage
      - codecov/upload:
          file: ./coverage/clover.xml

workflows:
  build-and-test:
    jobs:
      - build-and-test
