version: 2.1

orbs:
  node: circleci/node@3.0.0
  codecov: codecov/codecov@1.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: latest
      - run: npm install
      - run: npm run lint
      - run: npm test
      - codecov/upload:
          file: ./coverage/clover.xml

workflows:
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master
                - develop
                - /pulls\/.*/