version: 2.1

orbs:
  codecov: codecov/codecov@1.1.0

jobs:
  build-and-test:
    docker:
      - image: cypress/included:9.5.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v2-npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - /root/.cache/Cypress
      - run: npm run lint
      - run: npm run tests
      - codecov/upload:
          file: ./coverage/clover.xml

workflows:
  build-and-test:
    jobs:
      - build-and-test
