version: 2.1

orbs:
  codecov: codecov/codecov@1.1.0

jobs:
  build-and-test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm test
      - codecov/upload:
          file: ./coverage/clover.xml

workflows:
  build-and-test:
    jobs:
      - build-and-test
